# Specify the base image with the desired Node.js version
FROM node:16.3.0-alpine

# Set the working directory in the container
WORKDIR /app

# Copy the package.json and package-lock.json files to the working directory
COPY package*.json ./

# Run npm install to install the dependencies
RUN npm install

# Copy the rest of the application files to the working directory
COPY . .
 

# Start the application
CMD [ "npm", "start" ]